### ISSUE TITLE
Whiteboard design session - SME review comments

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/Building-the-business-migration-case-with-Windows-Server-and-SQL-Server#1]
### MCW SMEs
Thank you for your review!  Please leave your feedback for our authors below.

**Comment by DawnmarieDesJardins** [comment]
Hello!  Here's are the notes from my QC.  Let me know if there's anything that doesn't make sense.

[WDS - PM QC_Review.docx](https://github.com/solliancenet/Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/files/9579318/WDS.-.PM.QC_Review.docx)

**Comment by daneenec** [comment]
> Hello! Here's are the notes from my QC. Let me know if there's anything that doesn't make sense.
> 
> [WDS - PM QC_Review.docx](https://github.com/solliancenet/Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/files/9579318/WDS.-.PM.QC_Review.docx)

Thanks Dawnmarie, Chris is working on the update this afternoon!

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins The items in the QC notes you sent have been addressed and are committed to the repo.

**Comment by DawnmarieDesJardins** [comment]
Thanks Chris!  I see a couple more things:
On the student guide, objection #2 is different from the trainer guide. 
Need to move the updated abstract to the ReadMe page, or make sure we use the correct one when we move it into the MS repo.

Since the guides are complete, I QC'd the PPT, here's what I see:
Abstract needs to be updated to match guides
Customer situation section - some of the points have periods, some don't.  Full sentences with punctuation or not full sentences, they need to be consistent.
Slide 5 - identifies should be identified
Slides 7 & 8 - the objection questions are different than in the trainer guide 
Slide 15 - fix the font/bold please
Slide 17 - semicolon after used
Slide order - The preferred solution part of the presentation confused me a little.  I expected to see the solution diagram first, before the overview questions (following the trainer guide).  We're missing some of subtitles we added to the trainer guide in the PPT, high-level overview, migration, on-premises workload management.  The pricing section is there but looks very different than the trainer guide, only 1 image and no explanation, no total estimated cost.

**Comment by DawnmarieDesJardins** [comment]
Opps, one more, sorry.  Trainer guide, Customer objection #4:  
Azure Arc provides the ability **to** manage all your VMs and servers across both on-premises and Azure from a single place.

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins These addition items have been addressed.

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Thanks Chris!  We can move the WDS docs over the Microsoft repo now.

Microsoft repo:
[microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server](https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/)

**Comment by crpietschmann** [comment]
@Dawnmarie DesJardins (GP Strategies ***@***.***> I created a PR with the WDS on the MCW project, but I don’t have permissions to merge it in. Would you please merge it or me? Thanks!

--
Chris Pietschmann


From: Dawnmarie DesJardins ***@***.***>
Date: Monday, September 19, 2022 at 2:56 PM
To: solliancenet/Building-the-business-migration-case-with-Windows-Server-and-SQL-Server ***@***.***>
Cc: Chris Pietschmann ***@***.***>, Mention ***@***.***>
Subject: Re: [solliancenet/Building-the-business-migration-case-with-Windows-Server-and-SQL-Server] Whiteboard design session - SME review comments (Issue #1)

@crpietschmann<https://github.com/crpietschmann>
Thanks Chris! We can move the WDS docs over the Microsoft repo now.

Microsoft repo:
microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server<https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/>

**Comment by DawnmarieDesJardins** [comment]
Done, thank you!
